-- MySQL Script generated by MySQL Workbench
-- Fri Mar 27 09:13:55 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema reservation_bot
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema reservation_bot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `reservation_bot` DEFAULT CHARACTER SET utf8 ;
USE `reservation_bot` ;

-- -----------------------------------------------------
-- Table `reservation_bot`.`USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reservation_bot`.`USERS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NULL,
  `PERMISSION` INT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reservation_bot`.`PERMISSIONS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reservation_bot`.`PERMISSIONS` (
  `ID` INT NOT NULL,
  `NAME` VARCHAR(45) NULL,
  `DESCRIPTION` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reservation_bot`.`RESOURCES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reservation_bot`.`RESOURCES` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NULL,
  `DESCRIPTION` VARCHAR(255) NULL,
  `USER` INT NULL,
  `STATE` INT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reservation_bot`.`STATES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reservation_bot`.`STATES` (
  `ID` INT NOT NULL,
  `NAME` VARCHAR(45) NULL,
  `DESCRIPTION` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

