-- MySQL Script generated by MySQL Workbench
-- Thu Mar 26 21:08:09 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema RESERVATION_BOT
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema RESERVATION_BOT
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RESERVATION_BOT` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `RESERVATION_BOT` ;

-- -----------------------------------------------------
-- Table `RESERVATION_BOT`.`STATES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RESERVATION_BOT`.`STATES` (
  `ID` INT NOT NULL,
  `NAME` VARCHAR(45) NULL,
  `DESCRIPTION` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RESERVATION_BOT`.`RESOURCES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RESERVATION_BOT`.`RESOURCES` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NULL,
  `DESCRIPTION` VARCHAR(45) NULL,
  `STATE_ID` INT NULL,
  `USER_ID` INT NULL,
  `STATES_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  INDEX `fk_RESOURCES_STATES1_idx` (`STATES_ID` ASC),
  CONSTRAINT `fk_RESOURCES_STATES1`
    FOREIGN KEY (`STATES_ID`)
    REFERENCES `RESERVATION_BOT`.`STATES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RESERVATION_BOT`.`PERMISSIONS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RESERVATION_BOT`.`PERMISSIONS` (
  `ID` INT NOT NULL,
  `PERMISSIONS` VARCHAR(45) NULL,
  `DESCRIPTION` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RESERVATION_BOT`.`USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RESERVATION_BOT`.`USERS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NULL,
  `PERMISSION_ID` INT NULL,
  `RESOURCES_ID` INT NOT NULL,
  `PERMISSIONS_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  INDEX `fk_USERS_RESOURCES_idx` (`RESOURCES_ID` ASC),
  INDEX `fk_USERS_PERMISSIONS1_idx` (`PERMISSIONS_ID` ASC),
  CONSTRAINT `fk_USERS_RESOURCES`
    FOREIGN KEY (`RESOURCES_ID`)
    REFERENCES `RESERVATION_BOT`.`RESOURCES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USERS_PERMISSIONS1`
    FOREIGN KEY (`PERMISSIONS_ID`)
    REFERENCES `RESERVATION_BOT`.`PERMISSIONS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
